name = "my-first-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Uncomment to use KV storage
# kv_namespaces = [
#   { binding = "MY_KV", id = "your-kv-namespace-id" }
# ]

# Environment variables for production
[env.production.vars]
ENVIRONMENT = "production"

# Environment variables for development
[env.development.vars]
ENVIRONMENT = "development" 